### ISSUE TITLE
Unhandled exception occurred in '2.4-dev#17'

### ISSUE THREAD

**Issue by ayzikhn18** [commixproject/commix#198]
Hi, i have downloaded commix from github , wehen i run it i get this message and it wont go any further.

"
[x] Critical: Unhandled exception occurred in '2.4-dev#17'. It is recommended to retry your run with the latest (dev) version from official GitHub repository at 'https://github.com/commixproject/commix.git'. If the exception persists, please open a new issue at 'https://github.com/commixproject/commix/issues/new' with the following text and any other information required to reproduce the bug. The developers will try to reproduce the bug, fix it accordingly and get back to you.
Commix version: 2.4-dev#17
Python version: 2.7.14
Operating system: posix
Command line: commix.py

Traceback (most recent call last):
  File "commix.py", line 31, in <module>
    import src.core.main
  File "main.py", line 29, in <module>
    from src.utils import logs
  File "logs.py", line 21, in <module>
    import sqlite3
  File "__init__.py", line 24, in <module>
    from dbapi2 import *
  File "dbapi2.py", line 28, in <module>
    from _sqlite3 import *
ImportError: No module named _sqlite3
"

any solution for this please. Thank You

**Comment by stasinopoulos** [comment]
Hey, could you please provide me with more information about this bug i.e. the command(s) you have entered.

**Comment by ayzikhn18** [comment]
I have update Dev but still facing this problem,

**Comment by Sahabalam** [comment]
getting error like this,
python --version:3.8.2
Command line: commix.py --url=**************************************** --cookie=***************** PHPSESSID=finngikbqq7lajp0agrvlls452 --data=*******************************
Traceback (most recent call last):
  File "commix.py", line 35, in <module>
    main()
  File "commix.py", line 30, in main
    import src.core.main
  File "main.py", line 907, in <module>
    main(filename, url)
  File "main.py", line 604, in main
    controller.do_check(url, filename)
  File "controller.py", line 684, in do_check
    perform_checks(url,filename)
  File "controller.py", line 608, in perform_checks
    basic_level_checks()
  File "controller.py", line 576, in basic_level_checks
    post_request(url, http_request_method, filename, timesec)
  File "controller.py", line 554, in post_request
    injection_proccess(url, check_parameter, http_request_method, filename, timesec)
  File "controller.py", line 144, in injection_proccess
    url = heuristic_basic(url, http_request_method)
  File "controller.py", line 89, in heuristic_basic
    response = requests.get_request_response(request)
  File "requests.py", line 250, in get_request_response
    headers.check_http_traffic(request)
  File "headers.py", line 162, in check_http_traffic
    opener.open(request)
  File "request.py", line 522, in open
    req = meth(req)
  File "request.py", line 1281, in do_request_
    raise TypeError(msg)
TypeError: POST data should be bytes, an iterable of bytes, or a file object. It cannot be of type str.
Do you want to automatically create a new (anonymized) issue with the unhandled exception information at the official Github repository? [y/N] y
Traceback (most recent call last):
  File "./commix.py", line 35, in <module>
    main()
  File "./commix.py", line 30, in main
    import src.core.main
  File "/usr/share/commix/src/core/main.py", line 907, in <module>
    main(filename, url)
  File "/usr/share/commix/src/core/main.py", line 604, in main
    controller.do_check(url, filename)
  File "/usr/share/commix/src/core/injections/controller/controller.py", line 684, in do_check
    perform_checks(url,filename)
  File "/usr/share/commix/src/core/injections/controller/controller.py", line 608, in perform_checks
    basic_level_checks()
  File "/usr/share/commix/src/core/injections/controller/controller.py", line 576, in basic_level_checks
    post_request(url, http_request_method, filename, timesec)
  File "/usr/share/commix/src/core/injections/controller/controller.py", line 554, in post_request
    injection_proccess(url, check_parameter, http_request_method, filename, timesec)
  File "/usr/share/commix/src/core/injections/controller/controller.py", line 144, in injection_proccess
    url = heuristic_basic(url, http_request_method)
  File "/usr/share/commix/src/core/injections/controller/controller.py", line 89, in heuristic_basic
    response = requests.get_request_response(request)
  File "/usr/share/commix/src/core/requests/requests.py", line 250, in get_request_response
    headers.check_http_traffic(request)
  File "/usr/share/commix/src/core/requests/headers.py", line 162, in check_http_traffic
    opener.open(request)
  File "/usr/lib/python3.8/urllib/request.py", line 522, in open
    req = meth(req)
  File "/usr/lib/python3.8/urllib/request.py", line 1281, in do_request_
    raise TypeError(msg)
TypeError: POST data should be bytes, an iterable of bytes, or a file object. It cannot be of type str.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./commix.py", line 48, in <module>
    common.unhandled_exception()
  File "/usr/share/commix/src/utils/common.py", line 226, in unhandled_exception
    create_github_issue(err_msg, exc_msg[:])
  File "/usr/share/commix/src/utils/common.py", line 96, in create_github_issue
    data = data.encode(json.dumps(data)), 
AttributeError: 'dict' object has no attribute 'encode'
