### ISSUE TITLE
Execution Error

### ISSUE THREAD

**Issue by Sydwicked** [commixproject/commix#397]
root@kali:~/commix# python commix.py -h
Traceback (most recent call last):
  File "commix.py", line 18, in <module>
    __import__("src.utils.version")
  File "/root/commix/src/utils/version.py", line 17, in <module>
    from src.utils import settings
  File "/root/commix/src/utils/settings.py", line 130
    print print_critical_msg(err_msg)
                           ^
SyntaxError: invalid syntax

OS: Linux kali 4.18.0-kali2-amd64 #1 SMP Debian 4.18.10-2kali1 (2018-10-09) x86_64 GNU/Linux
COMMIX version could not find. Cloned Repo today.

**Comment by stasinopoulos** [comment]
This is due to Incompatible Python version. Try to use Python 2.7
