### ISSUE TITLE
shellshock injection 

### ISSUE THREAD

**Issue by Narvalo999** [commixproject/commix#550]
Traceback (most recent call last):
  File "/usr/local/bin/commix", line 11, in <module>
    load_entry_point('commix==3.2.dev0', 'console_scripts', 'commix')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2421, in resolve
    raise ImportError(str(exc))
ImportError: 'module' object has no attribute 'entry_point'

Can i have help please ?

**Comment by stasinopoulos** [comment]
Hello @Narvalo999, could you please provide me with the running context details?

* Installation method (e.g. apt-get, git clone or zip/tar.gz)
* Client OS (e.g. Linux (Ubuntu))
* Program version (python commix.py --version or commix --version depending on installation):
* Target OS (e.g. Linux (Debian))
