### ISSUE TITLE
Commix error

### ISSUE THREAD

**Issue by Ny223** [commixproject/commix#551]
[critical] Unhandled exception occurred in '3.1-stable'. It is recommended to retry your run with the latest (dev) version from official GitHub repository at 'https://github.com/commixproject/commix.git'. If the exception persists, please open a new issue at 'https://github.com/commixproject/commix/issues/new' with the following text and any other information required to reproduce the bug. The developers will try to reproduce the bug, fix it accordingly and get back to you.
Commix version: 3.1-stable
Python version: 3.9.1rc1
Operating system: posix
Command line: commix.py --url=************************************* --cookie=***************** PHPSESSID=219c7a2ee8bf95169be56272e4a9645e --data=**********************************
Traceback (most recent call last):
  File "commix.py", line 35, in <module>
    main()
  File "commix.py", line 30, in main
    import src.core.main
  File "main.py", line 907, in <module>
    main(filename, url)
  File "main.py", line 604, in main
    controller.do_check(url, filename)
  File "controller.py", line 684, in do_check
    perform_checks(url,filename)
  File "controller.py", line 608, in perform_checks
    basic_level_checks()
  File "controller.py", line 576, in basic_level_checks
    post_request(url, http_request_method, filename, timesec)
  File "controller.py", line 554, in post_request
    injection_proccess(url, check_parameter, http_request_method, filename, timesec)
  File "controller.py", line 144, in injection_proccess
    url = heuristic_basic(url, http_request_method)
  File "controller.py", line 89, in heuristic_basic
    response = requests.get_request_response(request)
  File "requests.py", line 250, in get_request_response
    headers.check_http_traffic(request)
  File "headers.py", line 162, in check_http_traffic
    opener.open(request)
  File "request.py", line 514, in open
    req = meth(req)
  File "request.py", line 1273, in do_request_
    raise TypeError(msg)

**Comment by Ny223** [comment]
I was trying to improve myself with a training video via bWAPP and commix was used in the video. Although I did everything as in the video, I got such an error.I tried updating the commixi on github, but the error continued

**Comment by stasinopoulos** [comment]
Hello @Ny223, please try update to the latest (dev) version via using git.
