### ISSUE TITLE
Running on Windows

### ISSUE THREAD

**Issue by royshum93** [commixproject/commix#57]
When I try to run the script, I run into this error.

```
> python commix.py
Traceback (most recent call last):
  File "commix.py", line 41, in <module>
    from src.utils import logs
  File "d:\commix\src\utils\logs.py", line 23, in <module>
    import readline
ImportError: No module named readline
```

Later I learnt `readline` is not supported in Windows.

```
> pip install readline
Collecting readline
  Downloading readline-6.2.4.1.tar.gz (2.3MB)
    100% |################################| 2.3MB 340kB/s
    Complete output from command python setup.py egg_info:
    error: this module is not meant to work on Windows
```

**Comment by stasinopoulos** [comment]
Thanks for the bug report, I' ll check it out.
