### ISSUE TITLE
Bug Report: Unhandled exception "AttributeError: 'NoneType' object has no attribute 'group'"

### ISSUE THREAD

**Issue by commixreporter** [commixproject/commix#623]
```
Commix version: 3.2-dev#88
Python version: 2.7.18
Operating system: posix
Command line: commix.py --url=*************************************** --shellshock --random-agent

```
```
Traceback (most recent call last):
  File "commix.py", line 35, in <module>
    main()
  File "commix.py", line 30, in main
    import src.core.main
  File "main.py", line 899, in <module>
    main(filename, url)
  File "main.py", line 602, in main
    controller.do_check(url, filename)
  File "controller.py", line 711, in do_check
    perform_checks(url,filename)
  File "controller.py", line 635, in perform_checks
    basic_level_checks()
  File "controller.py", line 600, in basic_level_checks
    get_request(url, http_request_method, filename, timesec)
  File "controller.py", line 490, in get_request
    check_parameter = parameters.vuln_GET_param(url)
  File "parameters.py", line 192, in vuln_GET_param
    vuln_parameter = re.search(r'\?(.*)=', url).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by jmool9810** [comment]
jmo
