### ISSUE TITLE
Bug Report: Unhandled exception "SyntaxError: Missing parentheses in call to 'print'. Did you mean print("")?"

### ISSUE THREAD

**Issue by commixreporter** [commixproject/commix#648]
```
Commix version: 3.3-dev#38
Python version: 3.9.5
Operating system: posix
Command line: commix.py -u ******************************************************************************* --auth-cred=****************
```
```
Traceback (most recent call last):
  File "commix.py", line 35, in <module>
    main()
  File "commix.py", line 30, in main
    import src.core.main
  File "main.py", line 35, in <module>
    from src.utils import crawler
  File "crawler.py", line 75
    print ""
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("")?
```

**Comment by stasinopoulos** [comment]
Fixed https://github.com/commixproject/commix/commit/c3ee73adf2f2c6598c2a62c9eecdda3cc1f31b94
