### ISSUE TITLE
Bug Report: Unhandled exception "NameError: name 're' is not defined"

### ISSUE THREAD

**Issue by commixreporter** [commixproject/commix#664]
```
Commix version: 3.2-stable
Python version: 3.9.2
Operating system: posix
Command line: commix.py -u ******************** --crawl=2 --is-root --is-admin --level=3 --passwords --users --force-ssl --auth-cred=*********** --auth-type=digest

```
```
Traceback (most recent call last):
  File "redirection.py", line 101, in do_check
    response = _urllib.request.urlopen(url, timeout=settings.TIMEOUT)
  File "request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "request.py", line 523, in open
    response = meth(req, response)
  File "request.py", line 632, in http_response
    response = self.parent.error(
  File "request.py", line 561, in error
    return self._call_chain(*args)
  File "request.py", line 494, in _call_chain
    result = func(*args)
  File "request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "commix.py", line 35, in <module>
    main()
  File "commix.py", line 30, in main
    import src.core.main
  File "main.py", line 903, in <module>
    response, url = url_response(url)
  File "main.py", line 301, in url_response
    url = redirection.do_check(url)
  File "redirection.py", line 105, in do_check
    authobj = re.match('''(\w*)\s+realm=(.*),''',authline).groups()
NameError: name 're' is not defined
```

**Comment by stasinopoulos** [comment]
Similar with https://github.com/commixproject/commix/issues/665
