### ISSUE TITLE
Bug Report: Unhandled exception "OSError: [Errno 22] Invalid argument: 'C:\\Users\\Welcome\\Desktop\\commix\\src\\core\\shells\\reverse_tcp.py'"

### ISSUE THREAD

**Issue by commixreporter** [commixproject/commix#671]
```
Commix version: 3.3-stable
Python version: 3.9.1
Operating system: nt
Command line: commix.py --url=*************************************** --cookie=******************************************* security_level=1 --data=******************************
```
```
Traceback (most recent call last):
  File "commix.py", line 35, in <module>
    main()
  File "commix.py", line 30, in main
    import src.core.main
  File "main.py", line 48, in <module>
    from src.core.injections.controller import controller
  File "controller.py", line 32, in <module>
    from src.core.injections.blind.techniques.time_based import tb_handler
  File "tb_handler.py", line 32, in <module>
    from src.core.injections.controller import shell_options
  File "shell_options.py", line 24, in <module>
    from src.core.shells import reverse_tcp
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 786, in exec_module
  File "<frozen importlib._bootstrap_external>", line 922, in get_code
  File "<frozen importlib._bootstrap_external>", line 979, in get_data
OSError: [Errno 22] Invalid argument: 'C:\\Users\\Welcome\\Desktop\\commix\\src\\core\\shells\\reverse_tcp.py'
```

**Comment by stasinopoulos** [comment]
Seems invalid due to: 
![Screenshot 2021-09-19 at 1 07 16 PM](https://user-images.githubusercontent.com/5289251/133923666-618cd351-1e08-44ce-b918-44d636bfde88.png)
