### ISSUE TITLE
Bug Report: Unhandled exception "UnicodeEncodeError: 'charmap' codec can't encode character '\ufeff' in position 27950: character maps to <undefined>"

### ISSUE THREAD

**Issue by commixreporter** [commixproject/commix#708]
```
Commix version: 3.3-stable
Python version: 3.7.4
Operating system: nt
Command line: commix.py -u *************************** --ignore-redirects --level=3 --os=Unix -t rohininilekani.org.commix.txt

```
```
Traceback (most recent call last):
  File "commix.py", line 35, in <module>
    main()
  File "commix.py", line 30, in main
    import src.core.main
  File "main.py", line 912, in <module>
    response, url = url_response(url)
  File "main.py", line 298, in url_response
    response = examine_request(request)
  File "main.py", line 105, in examine_request
    headers.check_http_traffic(request)
  File "headers.py", line 224, in check_http_traffic
    print_http_response(response_headers, code, page)
  File "headers.py", line 86, in print_http_response
    http_response_content(page)
  File "headers.py", line 53, in http_response_content
    logs.log_traffic(content)
  File "logs.py", line 178, in log_traffic
    output_file.write(header)
  File "cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\ufeff' in position 27950: character maps to <undefined>
```

**Comment by stasinopoulos** [comment]
Update to the latest (dev) version.
