### ISSUE TITLE
Bug Report: Unhandled exception "AttributeError: 'Values' object has no attribute 'DEFAULT_CRAWLDEPTH_LEVEL'"

### ISSUE THREAD

**Issue by commixreporter** [commixproject/commix#712]
```
Commix version: 3.2-stable
Python version: 3.9.2
Operating system: posix
Command line: commix.py -x *************************************
```
```
Traceback (most recent call last):
  File "commix.py", line 35, in <module>
    main()
  File "commix.py", line 30, in main
    import src.core.main
  File "main.py", line 906, in <module>
    main(filename, url)
  File "main.py", line 500, in main
    url = crawler.crawler(url)
  File "crawler.py", line 253, in crawler
    if menu.options.DEFAULT_CRAWLDEPTH_LEVEL > 1:
AttributeError: 'Values' object has no attribute 'DEFAULT_CRAWLDEPTH_LEVEL'
```

**Comment by stasinopoulos** [comment]
Update to the latest (dev) version.
