### ISSUE TITLE
Bug Report: Unhandled exception "UnicodeDecodeError: 'gbk' codec can't decode byte 0x9f in position 95: illegal multibyte sequence"

### ISSUE THREAD

**Issue by commixreporter** [commixproject/commix#716]
```
Commix version: 3.3-dev#36
Python version: 3.8.5
Operating system: nt
Command line: commix.py -r ******
```
```
Traceback (most recent call last):
  File "commix.py", line 35, in <module>
    main()
  File "commix.py", line 30, in main
    import src.core.main
  File "main.py", line 914, in <module>
    filename = logs_filename_creation()
  File "main.py", line 358, in logs_filename_creation
    filename = logs.create_log_file(url, output_dir)
  File "logs.py", line 88, in create_log_file
    checks.load_cmd_history()
  File "checks.py", line 94, in load_cmd_history
    readline.read_history_file(cli_history)
  File "rlmain.py", line 165, in read_history_file
    self.mode._history.read_history_file(filename)
  File "history.py", line 82, in read_history_file
    for line in open(filename, 'r'):
UnicodeDecodeError: 'gbk' codec can't decode byte 0x9f in position 95: illegal multibyte sequence
```

**Comment by stasinopoulos** [comment]
Note: https://github.com/pyreadline/pyreadline/issues/30
