### ISSUE TITLE
Bug Report: Unhandled exception "AttributeError: module 'src.utils.settings' has no attribute 'SINGLE_WHITESPACE'"

### ISSUE THREAD

**Issue by commixreporter** [commixproject/commix#720]
```
Commix version: 3.2-stable
Python version: 3.9.9
Operating system: posix
Command line: commix.py

```
```
Traceback (most recent call last):
  File "main.py", line 686, in <module>
    raise SystemExit()
SystemExit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "commix.py", line 35, in <module>
    main()
  File "commix.py", line 30, in main
    import src.core.main
  File "main.py", line 936, in <module>
    print(settings.SINGLE_WHITESPACE)
AttributeError: module 'src.utils.settings' has no attribute 'SINGLE_WHITESPACE'
```

**Comment by stasinopoulos** [comment]
Update to the latest (dev) version.
