### ISSUE TITLE
Unhandled Error 

### ISSUE THREAD

**Issue by Anthonymcqueen21** [commixproject/commix#722]
[critical] Unhandled exception occurred in '3.4-dev#28'. It is recommended to retry your run with the latest (dev) version from official GitHub repository at 'https://github.com/commixproject/commix.git'. If the exception persists, please open a new issue at 'https://github.com/commixproject/commix/issues/new' with the following text and any other information required to reproduce the bug. The developers will try to reproduce the bug, fix it accordingly and get back to you.
Commix version: 3.4-dev#28
Python version: 3.9.8
Operating system: posix
Command line: commix.py --url ********************************************* --batch --level=1

Traceback (most recent call last):
  File "commix.py", line 35, in <module>
    main()
  File "commix.py", line 30, in main
    import src.core.main
  File "main.py", line 922, in <module>
    main(filename, url)
  File "main.py", line 617, in main
    controller.do_check(url, http_request_method, filename)
  File "controller.py", line 747, in do_check
    perform_checks(url, http_request_method, filename)
  File "controller.py", line 670, in perform_checks
    basic_level_checks()
  File "controller.py", line 638, in basic_level_checks
    get_request(url, http_request_method, filename, timesec)
  File "controller.py", line 549, in get_request
    injection_proccess(url, check_parameter, http_request_method, filename, timesec)
  File "controller.py", line 291, in injection_proccess
    url = heuristic_basic(url, http_request_method)
  File "controller.py", line 109, in heuristic_basic
    response = requests.get_request_response(request)
  File "requests.py", line 255, in get_request_response
    headers.check_http_traffic(request)
  File "headers.py", line 172, in check_http_traffic
    response = opener.open(request, timeout=settings.TIMEOUT)
  File "request.py", line 517, in open
    response = self._open(req, data)
  File "request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "request.py", line 494, in _call_chain
    result = func(*args)
  File "headers.py", line 139, in https_open
    self.do_open(connection, req)
  File "request.py", line 1346, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "client.py", line 1326, in _send_request
    self.putheader(hdr, value)
  File "client.py", line 1262, in putheader
    if _is_illegal_header_value(values[i]):
TypeError: expected string or bytes-like object

I wanted to use a simple "INJECT_HERE" and this happened ?

**Comment by stasinopoulos** [comment]
Try to update to the latest dev version and use the "-p" option in order to define the testable parameter(s).

**Comment by Anthonymcqueen21** [comment]
Okay thanks
