### ISSUE TITLE
Bug Report: Unhandled exception "AttributeError: module 'collections' has no attribute 'Callable'"

### ISSUE THREAD

**Issue by commixreporter** [commixproject/commix#727]
```
Commix version: 3.4-dev#34
Python version: 3.10.0
Operating system: nt
Command line: commix.py --url=************************* --all

```
```
Traceback (most recent call last):
  File "commix.py", line 35, in <module>
    main()
  File "commix.py", line 30, in main
    import src.core.main
  File "main.py", line 29, in <module>
    from src.utils import logs
  File "logs.py", line 24, in <module>
    from src.core.injections.controller import checks
  File "checks.py", line 41, in <module>
    import readline
  File "readline.py", line 34, in <module>
    rl = Readline()
  File "rlmain.py", line 422, in __init__
    BaseReadline.__init__(self)
  File "rlmain.py", line 62, in __init__
    mode.init_editing_mode(None)
  File "emacs.py", line 633, in init_editing_mode
    self._bind_key('space',       self.self_insert)
  File "basemode.py", line 162, in _bind_key
    if not callable(func):
  File "py3k_compat.py", line 8, in callable
    return isinstance(x, collections.Callable)
AttributeError: module 'collections' has no attribute 'Callable'
```

**Comment by stasinopoulos** [comment]
Similar with https://github.com/commixproject/commix/issues/728
