### ISSUE TITLE
Bug Report: Unhandled exception "AttributeError: 'NoneType' object has no attribute 'read'"

### ISSUE THREAD

**Issue by commixreporter** [commixproject/commix#735]
```
Commix version: 3.3-stable
Python version: 3.9.8
Operating system: posix
Command line: commix.py -x *************************************
```
```
Traceback (most recent call last):
  File "commix.py", line 35, in <module>
    main()
  File "commix.py", line 30, in main
    import src.core.main
  File "main.py", line 915, in <module>
    main(filename, url)
  File "main.py", line 497, in main
    url = crawler.crawler(url)
  File "crawler.py", line 252, in crawler
    output_href = do_process(url)
  File "crawler.py", line 162, in do_process
    for url in crawling(url):
  File "crawler.py", line 125, in crawling
    content = checks.page_encoding(response, action="decode")
  File "checks.py", line 154, in page_encoding
    page = response.read()
AttributeError: 'NoneType' object has no attribute 'read'
```

**Comment by stasinopoulos** [comment]
Update to the latest (dev) version.
