### ISSUE TITLE
Bug Report: Unhandled exception "BadStatusLine: No status line received - the server has closed the connection"

### ISSUE THREAD

**Issue by commixreporter** [commixproject/commix#745]
```
Commix version: 3.3-stable
Python version: 2.7.17
Operating system: posix
Command line: /usr/local/bin/commix -m V.txt

```
```
Traceback (most recent call last):
  File "/usr/local/bin/commix", line 35, in <module>
    main()
  File "/usr/local/bin/commix", line 30, in main
    import src.core.main
  File "main.py", line 878, in <module>
    response, url = url_response(url)
  File "main.py", line 298, in url_response
    response = examine_request(request)
  File "main.py", line 105, in examine_request
    headers.check_http_traffic(request)
  File "headers.py", line 217, in check_http_traffic
    response = _urllib.request.urlopen(request, timeout=settings.TIMEOUT)
  File "urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "urllib2.py", line 429, in open
    response = self._open(req, data)
  File "urllib2.py", line 447, in _open
    '_open', req)
  File "urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "urllib2.py", line 1248, in https_open
    context=self._context)
  File "urllib2.py", line 1208, in do_open
    r = h.getresponse(buffering=True)
  File "httplib.py", line 1178, in getresponse
    response.begin()
  File "httplib.py", line 452, in begin
    version, status, reason = self._read_status()
  File "httplib.py", line 416, in _read_status
    raise BadStatusLine("No status line received - the server has closed the connection")
BadStatusLine: No status line received - the server has closed the connection
```

**Comment by stasinopoulos** [comment]
Update to the latest (dev) version.
