### ISSUE TITLE
Bug Report: Unhandled exception "http.client.IncompleteRead: IncompleteRead(14308 bytes read, 4001 more expected)"

### ISSUE THREAD

**Issue by commixreporter** [commixproject/commix#746]
```
Commix version: 3.2-stable
Python version: 3.9.2
Operating system: posix
Command line: commix.py --url ********************************
```
```
Traceback (most recent call last):
  File "commix.py", line 35, in <module>
    main()
  File "commix.py", line 30, in main
    import src.core.main
  File "main.py", line 903, in <module>
    response, url = url_response(url)
  File "main.py", line 298, in url_response
    response = examine_request(request)
  File "main.py", line 105, in examine_request
    headers.check_http_traffic(request)
  File "headers.py", line 170, in check_http_traffic
    page = checks.page_encoding(response, action="encode")
  File "checks.py", line 154, in page_encoding
    page = response.read()
  File "client.py", line 471, in read
    s = self._safe_read(self.length)
  File "client.py", line 614, in _safe_read
    raise IncompleteRead(data, amt-len(data))
http.client.IncompleteRead: IncompleteRead(14308 bytes read, 4001 more expected)
```

**Comment by stasinopoulos** [comment]
Update to the latest (dev) version.
