### ISSUE TITLE
Bug Report: Unhandled exception "AttributeError: Values instance has no attribute 'MULTI_TARGETS'"

### ISSUE THREAD

**Issue by commixreporter** [commixproject/commix#757]
```
Commix version: 3.5-dev#34
Python version: 2.7.18
Operating system: posix
Command line: commix.py -m FUZZvuladulttime.com.txt

```
```
Traceback (most recent call last):
  File "commix.py", line 35, in <module>
    main()
  File "commix.py", line 30, in main
    import src.core.main
  File "main.py", line 806, in <module>
    if menu.options.MULTI_TARGETS:
AttributeError: Values instance has no attribute 'MULTI_TARGETS'
```

**Comment by DonatoReis** [comment]
I have the same problem


<a href="https://ibb.co/Fzmqj5z"><img src="https://i.ibb.co/CQmsTbQ/Sem-t-tulo.png" alt="Sem-t-tulo" border="0"></a>

**Comment by nutsinu** [comment]
Same here. Is there a temporary DIY fix?
