### ISSUE TITLE
Bug Report: Unhandled exception "KeyError: 'mpl_toolkits.legacy_colorbar'"

### ISSUE THREAD

**Issue by commixreporter** [commixproject/commix#764]
```
Commix version: 3.3-dev#36
Python version: 3.9.12
Operating system: posix
Command line: commix.py -u *********************** --random-agent --all --file-read=FILE.. --icmp-exfil=IP_.. --web-root=WEB_R.. --level=3 --skip-waf

```
```
Traceback (most recent call last):
  File "commix.py", line 35, in <module>
    main()
  File "commix.py", line 30, in main
    import src.core.main
  File "main.py", line 915, in <module>
    main(filename, url)
  File "main.py", line 615, in main
    controller.do_check(url, http_request_method, filename)
  File "controller.py", line 727, in do_check
    perform_checks(url, http_request_method, filename)
  File "controller.py", line 656, in perform_checks
    stored_http_header_injection(url, check_parameter, http_request_method, filename, timesec)
  File "controller.py", line 436, in stored_http_header_injection
    http_headers_injection(url, http_request_method, filename, timesec)
  File "controller.py", line 395, in http_headers_injection
    user_agent_injection(url, http_request_method, filename, timesec)
  File "controller.py", line 364, in user_agent_injection
    injection_proccess(url, check_parameter, http_request_method, filename, timesec)
  File "controller.py", line 276, in injection_proccess
    modules_handler.load_modules(url, http_request_method, filename)
  File "modules_handler.py", line 32, in load_modules
    from src.core.modules.icmp_exfiltration import icmp_exfiltration
  File "icmp_exfiltration.py", line 39, in <module>
    from scapy.all import *
  File "all.py", line 16, in <module>
    from scapy.arch import *
  File "__init__.py", line 55, in <module>
    from scapy.arch.linux import *  # noqa F403
  File "linux.py", line 27, in <module>
    from scapy.packet import Packet, Padding
  File "packet.py", line 36, in <module>
    from scapy.extlib import PYX
  File "extlib.py", line 21, in <module>
    from matplotlib import get_backend as matplotlib_get_backend
  File "__init__.py", line 928, in <module>
    defaultParams = rcsetup.defaultParams = {
  File "__init__.py", line 931, in <dictcomp>
    rcParamsDefault[key]),
  File "__init__.py", line 710, in __getitem__
    return dict.__getitem__(self, key)
KeyError: 'mpl_toolkits.legacy_colorbar'
```

**Comment by stasinopoulos** [comment]
Update to the latest (dev) version
