### ISSUE TITLE
Bug Report: Unhandled exception "TypeError: Odd-length string"

### ISSUE THREAD

**Issue by commixreporter** [commixproject/commix#765]
```
Commix version: 3.5-dev#50
Python version: 2.7.18
Operating system: posix
Command line: commix.py -u ****************************************************** -v1

```
```
Traceback (most recent call last):
  File "commix.py", line 35, in <module>
    main()
  File "commix.py", line 30, in main
    import src.core.main
  File "main.py", line 836, in <module>
    main(filename, url)
  File "main.py", line 488, in main
    controller.do_check(url, http_request_method, filename)
  File "controller.py", line 842, in do_check
    perform_checks(url, http_request_method, filename)
  File "controller.py", line 770, in perform_checks
    get_request(url, http_request_method, filename, timesec)
  File "controller.py", line 650, in get_request
    injection_proccess(url, check_parameter, http_request_method, filename, timesec)
  File "controller.py", line 375, in injection_proccess
    decoded_value, decoded_with = checks.recognise_payload(payload=settings.TESTABLE_VALUE)
  File "checks.py", line 1258, in recognise_payload
    decoded_payload, _ = hexdecode(check_value)
  File "convert.py", line 28, in hexdecode
    value = codecs.decode(''.join(value.split()), "hex")
  File "hex_codec.py", line 42, in hex_decode
    output = binascii.a2b_hex(input)
TypeError: Odd-length string
```

**Comment by stasinopoulos** [comment]
Update to latest (dev) version.
