### ISSUE TITLE
Bug Report: Unhandled exception "http.client.IncompleteRead: IncompleteRead(1354 bytes read)"

### ISSUE THREAD

**Issue by commixreporter** [commixproject/commix#771]
```
Commix version: 3.3-stable
Python version: 3.9.10
Operating system: posix
Command line: commix.py -u ********************************
```
```
Traceback (most recent call last):
  File "client.py", line 560, in _get_chunk_left
    chunk_left = self._read_next_chunk_size()
  File "client.py", line 527, in _read_next_chunk_size
    return int(line, 16)
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "client.py", line 577, in _readall_chunked
    chunk_left = self._get_chunk_left()
  File "client.py", line 562, in _get_chunk_left
    raise IncompleteRead(b'')
http.client.IncompleteRead: IncompleteRead(0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "commix.py", line 35, in <module>
    main()
  File "commix.py", line 30, in main
    import src.core.main
  File "main.py", line 912, in <module>
    response, url = url_response(url)
  File "main.py", line 298, in url_response
    response = examine_request(request)
  File "main.py", line 105, in examine_request
    headers.check_http_traffic(request)
  File "headers.py", line 173, in check_http_traffic
    page = checks.page_encoding(response, action="encode")
  File "checks.py", line 154, in page_encoding
    page = response.read()
  File "client.py", line 470, in read
    return self._readall_chunked()
  File "client.py", line 584, in _readall_chunked
    raise IncompleteRead(b''.join(value))
http.client.IncompleteRead: IncompleteRead(1354 bytes read)
```

**Comment by stasinopoulos** [comment]
Update to the latest (dev) version
