### ISSUE TITLE
Bug Report: Unhandled exception "ValueError: Invalid format '%(message)s' for '%' style"

### ISSUE THREAD

**Issue by commixreporter** [commixproject/commix#776]
```
Commix version: 3.4-stable
Python version: 3.10.4
Operating system: posix
Command line: commix.py -u ********************************
```
```
Traceback (most recent call last):
  File "commix.py", line 35, in <module>
    main()
  File "commix.py", line 30, in main
    import src.core.main
  File "main.py", line 35, in <module>
    from src.utils import crawler
  File "crawler.py", line 25, in <module>
    from src.thirdparty.beautifulsoup.beautifulsoup import BeautifulSoup
  File "beautifulsoup.py", line 1755, in <module>
    import chardet
  File "__init__.py", line 19, in <module>
    from .universaldetector import UniversalDetector
  File "universaldetector.py", line 40, in <module>
    import logging
  File "__init__.py", line 700, in <module>
    _defaultFormatter = Formatter()
  File "__init__.py", line 589, in __init__
    self._style.validate()
  File "__init__.py", line 429, in validate
    raise ValueError("Invalid format '%s' for '%s' style" % (self._fmt, self.default_format[0]))
ValueError: Invalid format '%(message)s' for '%' style
```

**Comment by stasinopoulos** [comment]
Update to latest (dev) version.
