### ISSUE TITLE
Bug Report: Unhandled exception "AssertionError: expected name token at "<!\x01\x0fbN\x1d\x01Y8'r\x1d\x7fiPؾ^m)""

### ISSUE THREAD

**Issue by commixreporter** [commixproject/commix#795]
```
Commix version: 3.4-stable
Python version: 3.10.4
Operating system: posix
Command line: commix.py --crawl=2 -u *********************
```
```
Traceback (most recent call last):
  File "commix.py", line 35, in <module>
    main()
  File "commix.py", line 30, in main
    import src.core.main
  File "main.py", line 946, in <module>
    main(filename, url)
  File "main.py", line 499, in main
    url = crawler.crawler(url)
  File "crawler.py", line 278, in crawler
    output_href = do_process(url)
  File "crawler.py", line 161, in do_process
    for url in crawling(url):
  File "crawler.py", line 128, in crawling
    soup = BeautifulSoup(content)
  File "beautifulsoup.py", line 1539, in __init__
    BeautifulStoneSoup.__init__(self, *args, **kwargs)
  File "beautifulsoup.py", line 1164, in __init__
    self._feed(isHTML=isHTML)
  File "beautifulsoup.py", line 1206, in _feed
    sgmllib.SGMLParser.feed(self, markup)
  File "sgmllib.py", line 98, in feed
    self.goahead(0)
  File "sgmllib.py", line 168, in goahead
    k = self.parse_declaration(i)
  File "beautifulsoup.py", line 1480, in parse_declaration
    j = sgmllib.SGMLParser.parse_declaration(self, i)
  File "_markupbase.py", line 93, in parse_declaration
    decltype, j = self._scan_name(j, i)
  File "_markupbase.py", line 390, in _scan_name
    raise AssertionError(
AssertionError: expected name token at "<!\x01\x0fbN\x1d\x01Y8'r\x1d\x7fiPؾ^m)"
```

**Comment by stasinopoulos** [comment]
Update to the latest (dev) version
