### ISSUE TITLE
Bug Report: Unhandled exception "ValueError: invalid literal for int() with base 10: 'j'" (#ec34f87f)

### ISSUE THREAD

**Issue by commixreporter** [commixproject/commix#801]
```
Commix version: 3.7-dev#13
Python version: 3.11.1
Operating system: posix
Command line: commix.py --wizard

```
```
Traceback (most recent call last):
  File "commix.py", line 35, in <module>
    main()
  File "commix.py", line 30, in main
    import src.core.main
  File "main.py", line 739, in <module>
    menu.options.level = int(common.read_input(message, default=settings.DEFAULT_INJECTION_LEVEL, check_batch=True))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'j'
```

**Comment by stasinopoulos** [comment]
Similar with https://github.com/commixproject/commix/issues/802
