### ISSUE TITLE
Bug Report: Unhandled exception "NameError: name 'version' is not defined" (#53ff9e7b)

### ISSUE THREAD

**Issue by commixreporter** [commixproject/commix#804]
```
Commix version: 3.7-dev#21
Python version: 3.10.4
Operating system: posix
Command line: commix.py

```
```
Traceback (most recent call last):
  File "commix.py", line 35, in <module>
    main()
  File "commix.py", line 30, in main
    import src.core.main
  File "main.py", line 28, in <module>
    from src.utils import logs
  File "logs.py", line 19, in <module>
    import sqlite3
  File "__init__.py", line 57, in <module>
    from sqlite3.dbapi2 import *
  File "dbapi2.py", line 49, in <module>
    version_info = tuple([int(x) for x in version.split(".")])
NameError: name 'version' is not defined
```

**Comment by stasinopoulos** [comment]
This is some kind of an environment problem.
