### ISSUE TITLE
Bug Report: Unhandled exception "AttributeError: 'function' object has no attribute 'glob'" (#ac9ca8f3)

### ISSUE THREAD

**Issue by commixreporter** [commixproject/commix#812]
```
Commix version: 3.7-dev#48
Python version: 3.10.8
Operating system: nt
Command line: commix.py --list-tampers

```
```
Traceback (most recent call last):
  File "commix.py", line 35, in <module>
    main()
  File "commix.py", line 30, in main
    import src.core.main
  File "main.py", line 574, in <module>
    checks.list_tamper_scripts()
  File "checks.py", line 1176, in list_tamper_scripts
    for script in sorted(glob.glob(os.path.join(settings.TAMPER_SCRIPTS_PATH, "*.py"))):
AttributeError: 'function' object has no attribute 'glob'
```

**Comment by stasinopoulos** [comment]
Not able to reproduce the issue.

- Windows 10 - Python 3.9.13

![Screenshot 2023-02-04 at 10 20 45 AM](https://user-images.githubusercontent.com/5289251/216757535-9103fdbe-9805-45ff-be98-cc18aff7bf81.png)

- Windows 10 - Python 3.11.1

![Screenshot 2023-02-04 at 10 32 32 AM](https://user-images.githubusercontent.com/5289251/216757530-240d681a-d616-4d98-b6b2-2b3484ebbeff.png)
