### ISSUE TITLE
Bug Report: Unhandled exception "AttributeError: 'NoneType' object has no attribute 'geturl'" (#19112601)

### ISSUE THREAD

**Issue by commixreporter** [commixproject/commix#813]
```
Commix version: 3.7-dev#56
Python version: 3.11.1
Operating system: nt
Command line: commix.py --url=***************************************** --prefix=' --suffix=//

```
```
Traceback (most recent call last):
  File "commix.py", line 35, in <module>
    main()
  File "commix.py", line 30, in main
    import src.core.main
  File "main.py", line 802, in <module>
    response, url = url_response(url)
                    ^^^^^^^^^^^^^^^^^
  File "main.py", line 226, in url_response
    if response.geturl() != url:
       ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'geturl'
```

**Comment by stasinopoulos** [comment]
Fixed https://github.com/commixproject/commix/commit/6b10092c1771a89b0417e5f4b2c989453549de3e
