### ISSUE TITLE
Bug Report: Unhandled exception "AttributeError: 'NoneType' object has no attribute 'geturl'" (#b4363aa8)

### ISSUE THREAD

**Issue by commixreporter** [commixproject/commix#814]
```
Commix version: 3.7-dev#56
Python version: 3.9.6
Operating system: posix
Command line: commix.py --url=************************************************ -c+10+127.0.0.1||&authuser=0||ping+-c+10+127.0.0.1||&format=INJECT_HERE --technique=t --cookie=************************************************************** -pZ5PDfMCyf34w; NID=511=g8OMvP4MWLOIpFfmDiyFZGXbypqdz75NOW7Yr_v40pXdZWPBVxArbKnoMIRjD_GSm2X-bdn5nThTQZ0oWL3YVyxwbpjJX96kVTlyYAiib_wRQil4BvKD4OaaAv6E82sYeD_6kqcEFsNiAH0G1o49bV8N7M9z0arM-HO97IDUaSE -v1

```
```
Traceback (most recent call last):
  File "commix.py", line 35, in <module>
    main()
  File "commix.py", line 30, in main
    import src.core.main
  File "main.py", line 802, in <module>
    response, url = url_response(url)
  File "main.py", line 226, in url_response
    if response.geturl() != url:
AttributeError: 'NoneType' object has no attribute 'geturl'
```

**Comment by stasinopoulos** [comment]
Similar with https://github.com/commixproject/commix/issues/813
