### ISSUE TITLE
Bug Report: Unhandled exception "AttributeError: 'NoneType' object has no attribute 'geturl'" (#19112601)

### ISSUE THREAD

**Issue by commixreporter** [commixproject/commix#815]
```
Commix version: 3.7-dev#56
Python version: 3.11.1
Operating system: posix
Command line: commix.py -u ************** -niger.com

```
```
Traceback (most recent call last):
  File "commix.py", line 35, in <module>
    main()
  File "commix.py", line 30, in main
    import src.core.main
  File "main.py", line 802, in <module>
    response, url = url_response(url)
                    ^^^^^^^^^^^^^^^^^
  File "main.py", line 226, in url_response
    if response.geturl() != url:
       ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'geturl'
```

**Comment by stasinopoulos** [comment]
Similar with https://github.com/commixproject/commix/issues/813
