### ISSUE TITLE
Bug Report: Unhandled exception "AttributeError: module 'collections' has no attribute 'Callable'" (#c3cb0ffe)

### ISSUE THREAD

**Issue by commixreporter** [commixproject/commix#823]
```
Commix version: 3.8-dev#5
Python version: 3.10.10
Operating system: nt
Command line: commix.py -u ********************** --all

```
```
Traceback (most recent call last):
  File "commix.py", line 35, in <module>
    main()
  File "commix.py", line 30, in main
    import src.core.main
  File "main.py", line 597, in <module>
    checks.third_party_dependencies()
  File "checks.py", line 943, in third_party_dependencies
    import readline
  File "readline.py", line 34, in <module>
    rl = Readline()
  File "rlmain.py", line 422, in __init__
    BaseReadline.__init__(self)
  File "rlmain.py", line 62, in __init__
    mode.init_editing_mode(None)
  File "emacs.py", line 633, in init_editing_mode
    self._bind_key('space',       self.self_insert)
  File "basemode.py", line 162, in _bind_key
    if not callable(func):
  File "py3k_compat.py", line 8, in callable
    return isinstance(x, collections.Callable)
AttributeError: module 'collections' has no attribute 'Callable'
```

**Comment by stasinopoulos** [comment]
A possible workaround is to uninstall the `pyreadline` package and install the [pyreadline3](https://pypi.org/project/pyreadline3/) package instead.
