### ISSUE TITLE
running error

### ISSUE THREAD

**Issue by w4rh34d-666** [commixproject/commix#833]
## What's the problem (or question)?

Traceback (most recent call last):
  File "/usr/local/bin/commix", line 11, in <module>
    load_entry_point('commix==3.8.dev0', 'console_scripts', 'commix')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/commix-3.8.dev0-py2.7.egg/src/core/main.py", line 28, in <module>
    from src.utils import logs
  File "/usr/local/lib/python2.7/dist-packages/commix-3.8.dev0-py2.7.egg/src/utils/logs.py", line 24, in <module>
    from src.core.injections.controller import checks
  File "/usr/local/lib/python2.7/dist-packages/commix-3.8.dev0-py2.7.egg/src/core/injections/controller/checks.py", line 32, in <module>
    from src.utils import logs
ImportError: cannot import name logs

## How can we reproduce the issue?
<--installation guide will be good -->
1.
2.
3.
4.

## What are the running context details?

* Installation method (e.g. `apt-get`, `git clone` or `zip`/`tar.gz`): zip
* Client OS (e.g. `Linux (Ubuntu)`)
* Program version (`python commix.py --version` or `commix --version` depending on installation): commix==3.8.dev0
* Target OS (e.g. `Linux (Debian)`): Linux backbox
* Command injection techniques found by commix (e.g. `classic (results-based)` and `time-based (blind)`):
* Results of manual target assessment (e.g. found that the payload `;echo \`id\`||echo $(whoami)` works):
* Relevant console output (if any):
```
Traceback (most recent call last):
  File "/usr/local/bin/commix", line 11, in <module>
    load_entry_point('commix==3.8.dev0', 'console_scripts', 'commix')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/commix-3.8.dev0-py2.7.egg/src/core/main.py", line 28, in <module>
    from src.utils import logs
  File "/usr/local/lib/python2.7/dist-packages/commix-3.8.dev0-py2.7.egg/src/utils/logs.py", line 24, in <module>
    from src.core.injections.controller import checks
  File "/usr/local/lib/python2.7/dist-packages/commix-3.8.dev0-py2.7.egg/src/core/injections/controller/checks.py", line 32, in <module>
    from src.utils import logs
ImportError: cannot import name logs
```
Traceback (most recent call last):
 
* Exception traceback (if any):

**Comment by stasinopoulos** [comment]
Hello @w4rh34d-666 , try to download commix by cloning the official Git repository:
`git clone https://github.com/commixproject/commix.git commix`

Regarding the reported issue, you may have to contact with your Linux distro maintenance / dev team.
