### ISSUE TITLE
Execution errors

### ISSUE THREAD

**Issue by sno0ose** [commixproject/commix#87]
Just came across your tool and wanted to check it out. I have a website that has shellshock and when I try to utilize I get this output. Not sure if anyone has had this issue previously,

[*] Checking connection to the target URL... [ SUCCEED ]
[*] Testing the shellshock injection technique... Traceback (most recent call last):
  File "./commix.py", line 1032, in <module>
    main(filename, url, init_test)
  File "./commix.py", line 816, in main
    controller.do_check(url, filename)
  File "/home/user/commix/src/core/injections/controller/controller.py", line 518, in do_check
    perform_checks(url,filename)
  File "/home/user/commix/src/core/injections/controller/controller.py", line 455, in perform_checks
    basic_level_checks()
  File "/home/user/commix/src/core/injections/controller/controller.py", line 420, in basic_level_checks
    get_request(url, http_request_method, filename, timesec)
  File "/home/user/commix/src/core/injections/controller/controller.py", line 346, in get_request
    injection_proccess(url, check_parameter, http_request_method, filename, timesec)
  File "/home/user/commix/src/core/injections/controller/controller.py", line 87, in injection_proccess
    modules_handler.load_modules(url, http_request_method, filename)
  File "/home/user/commix/src/core/modules/modules_handler.py", line 58, in load_modules
    shellshock.shellshock_handler(url, http_request_method, filename)
  File "/home/user/commix/src/core/modules/shellshock/shellshock.py", line 668, in shellshock_handler
    log_http_headers.check_http_traffic(request)
  File "/home/user/commix/src/core/requests/headers.py", line 136, in check_http_traffic
    opener.open(request)
  File "/usr/lib/python2.7/urllib2.py", line 421, in open
    protocol = req.get_type()
  File "/usr/lib/python2.7/urllib2.py", line 283, in get_type
    raise ValueError, "unknown url type: %s" % self.__original
ValueError: unknown url type: h

**Comment by stasinopoulos** [comment]
Hello and thanks for that bug report.
If it is possible, please provide more information (i.e. version of commix, provided commands etc) on that issue in order to understand the problem.
