### ISSUE TITLE
Bug Report: Unhandled exception "UnicodeEncodeError: 'ascii' codec can't encode characters in position 10-11: ordinal not in range(128)" (#77e253d5)

### ISSUE THREAD

**Issue by commixreporter** [commixproject/commix#880]
```
Commix version: 3.7-stable
Python version: 3.11.2
Operating system: posix
Command line: commix.py --url ********************************** --file-upload /root/桌面/test.php --file-dest E:/test/

```
```
Traceback (most recent call last):
  File "commix.py", line 35, in <module>
    main()
  File "commix.py", line 30, in main
    import src.core.main
  File "main.py", line 805, in <module>
    main(filename, url)
  File "main.py", line 473, in main
    _urllib.request.urlopen(menu.options.file_upload, timeout=settings.TIMEOUT)
  File "request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "request.py", line 519, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "request.py", line 1377, in http_open
    return self.do_open(http.client.HTTPConnection, req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "client.py", line 1293, in _send_request
    self.putrequest(method, url, **skips)
  File "client.py", line 1131, in putrequest
    self._output(self._encode_request(request))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "client.py", line 1211, in _encode_request
    return request.encode('ascii')
           ^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'ascii' codec can't encode characters in position 10-11: ordinal not in range(128)
```

**Comment by stasinopoulos** [comment]
Update to the latest (dev) version.
