### ISSUE TITLE
Bug Report: Unhandled exception "AttributeError: 'Values' object has no attribute 'ignore_stdin'" (#c5c65ede)

### ISSUE THREAD

**Issue by commixreporter** [commixproject/commix#890]
```
Commix version: 3.8-stable
Python version: 3.11.7
Operating system: posix
Command line: commix.py --wizard

```
```
Traceback (most recent call last):
  File "commix.py", line 35, in <module>
    main()
  File "commix.py", line 30, in main
    import src.core.main
  File "main.py", line 579, in <module>
    if hasattr(sys.stdin, "fileno") and not any((os.isatty(sys.stdin.fileno()), menu.options.ignore_stdin)):
                                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Values' object has no attribute 'ignore_stdin'
```

**Comment by stasinopoulos** [comment]
Update to the latest version.
