### ISSUE TITLE
Bug Report: Unhandled exception "TypeError: argument of type 'NoneType' is not iterable" (#4abac2d0)

### ISSUE THREAD

**Issue by commixreporter** [commixproject/commix#898]
```
Commix version: 4.0-dev#18
Python version: 3.11.8
Operating system: posix
Command line: commix.py --wizard

```
```
Traceback (most recent call last):
  File "commix.py", line 35, in <module>
    main()
  File "commix.py", line 30, in main
    import src.core.main
  File "main.py", line 867, in <module>
    main(filename, url)
  File "main.py", line 535, in main
    controller.do_check(url, http_request_method, filename)
  File "controller.py", line 747, in do_check
    if perform_checks(url, http_request_method, filename) == False:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "controller.py", line 705, in perform_checks
    cookie_injection(url, http_request_method, filename, timesec)
  File "controller.py", line 534, in cookie_injection
    injection_proccess(url, check_parameter, http_request_method, filename, timesec)
  File "controller.py", line 279, in injection_proccess
    elif check_parameter.lower() not in menu.options.data:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by stasinopoulos** [comment]
Potential fix https://github.com/commixproject/commix/commit/ad0783905859d92a88e398e4f0f1d825ec01d0e2
