### ISSUE TITLE
Bug Report: Unhandled exception "SyntaxError: closing parenthesis '}' does not match opening parenthesis '(' on line 3009" (#4e3307c0)

### ISSUE THREAD

**Issue by commixreporter** [commixproject/commix#901]
```
Commix version: 3.9-stable
Python version: 3.11.8
Operating system: posix
Command line: commix.py

```
```
Traceback (most recent call last):
  File "commix.py", line 35, in <module>
    main()
  File "commix.py", line 30, in main
    import src.core.main
  File "main.py", line 28, in <module>
    from src.utils import logs
  File "logs.py", line 25, in <module>
    from src.core.injections.controller import checks
  File "checks.py", line 39, in <module>
    from src.core.requests import requests
  File "requests.py", line 29, in <module>
    from src.utils import crawler
  File "crawler.py", line 31, in <module>
    from src.thirdparty.beautifulsoup.beautifulsoup import BeautifulSoup
  File "beautifulsoup.py", line 1755, in <module>
    import chardet
  File "__init__.py", line 24, in <module>
    from .universaldetector import UniversalDetector
  File "universaldetector.py", line 52, in <module>
    from .sbcsgroupprober import SBCSGroupProber
  File "sbcsgroupprober.py", line 45, in <module>
    from .langthaimodel import TIS_620_THAI_MODEL
  File "langthaimodel.py", line 3063
    },
    ^
SyntaxError: closing parenthesis '}' does not match opening parenthesis '(' on line 3009
```

**Comment by stasinopoulos** [comment]
Seems that something is wrong with Python environment.
