### ISSUE TITLE
No module named src.thirdparty.six.moves and print(settings.print_critical_msg(err_msg))

### ISSUE THREAD

**Issue by saltasatelites** [commixproject/commix#912]
Hello
Since the pytthon update, commix throws some error. I run commix on Arch Linux with commix cloned from Github, in a python environment and with the dependencies installed by pacman.  With python-3.11 all gets fine.
About `src.thirdparty.six.moves` I've seen another post, but nothing about `print(settings.print_critical_msg(err_msg))`

When I run `python commix.py `throws these errors:

```
Traceback (most recent call last):
  File "/home/me/.local/share/applications/pentest/commix/commix.py", line 18, in <module>
    __import__("src.utils.version")
  File "/home/me/.local/share/applications/pentest/commix/src/utils/version.py", line 17, in <module>
    from src.utils import settings
  File "/home/me/.local/share/applications/pentest/commix/src/utils/settings.py", line 26, in <module>
    from src.thirdparty.six.moves import urllib as _urllib
ModuleNotFoundError: No module named 'src.thirdparty.six.moves'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/me/.local/share/applications/pentest/commix/commix.py", line 25, in <module>
    print(settings.print_critical_msg(err_msg))
          ^^^^^^^^
```
Thanks in advance

**Comment by stasinopoulos** [comment]
Hello @saltasatelites this issue is similar with https://github.com/commixproject/commix/issues/871.

**Comment by stasinopoulos** [comment]
Hello @saltasatelites this issue is similar with https://github.com/commixproject/commix/issues/885.
