### ISSUE TITLE
Bug Report: Unhandled exception "TypeError: argument of type 'bool' is not iterable" (#e1e051ad)

### ISSUE THREAD

**Issue by commixreporter** [commixproject/commix#915]
```
Commix version: 4.0-dev#18
Python version: 3.11.8
Operating system: posix
Command line: commix.py --url=****************************************************** --cookie=*************** -p ***** 
```
```
Traceback (most recent call last):
  File "commix.py", line 35, in <module>
    main()
  File "commix.py", line 30, in main
    import src.core.main
  File "main.py", line 867, in <module>
    main(filename, url)
  File "main.py", line 535, in main
    controller.do_check(url, http_request_method, filename)
  File "controller.py", line 768, in do_check
    perform_checks(url, http_request_method, filename)
  File "controller.py", line 705, in perform_checks
    cookie_injection(url, http_request_method, filename, timesec)
  File "controller.py", line 528, in cookie_injection
    injection_proccess(url, check_parameter, http_request_method, filename, timesec)
  File "controller.py", line 279, in injection_proccess
    elif check_parameter.lower() not in menu.options.data:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'bool' is not iterable
```

**Comment by stasinopoulos** [comment]
Update to the latest (dev) version.
