### ISSUE TITLE
Bug Report: Unhandled exception "RecursionError: maximum recursion depth exceeded in comparison" (#24b37b9c)

### ISSUE THREAD

**Issue by commixreporter** [commixproject/commix#919]
```
Commix version: 4.0-dev#18
Python version: 3.10.2
Operating system: posix
Command line: commix.py --url=************************************************** --level=3 --crawl=2 --method=POST --data=********************************************************* -envelope"><soap:Header><context xmlns="urn:zimbra"><userAgent xmlns="" name="ZimbraWebClient - FF124 (Win)" version="8.8.15_GA_4257"/><session xmlns="" id="1624509"/><account xmlns="" by="name">test1@mail.zim15video.com</account><format xmlns="" type="js"/><csrfToken xmlns="">0_37500a3f3bf67109aa3c0520982558a97708a8c3</csrfToken></context></soap:Header><soap:Body><BatchRequest xmlns="urn:zimbra" onerror="continue"><DiscoverRightsRequest xmlns="urn:zimbraAccount" requestId="0"><right xmlns="">sendAs</right><right xmlns="">sendOnBehalfOf</right><right xmlns="">sendAsDistList</right><right xmlns="">sendOnBehalfOfDistList</right></DiscoverRightsRequest></BatchRequest></soap:Body></soap:Envelope> --cookie=*********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************** 
```
```
Traceback (most recent call last):
  File "pydevd_trace_dispatch_regular.py", line 359, in __call__
    is_stepping = pydev_step_cmd != -1
RecursionError: maximum recursion depth exceeded in comparison

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "commix.py", line 35, in <module>
    main()
  File "commix.py", line 30, in main
    import src.core.main
  File "main.py", line 27, in <module>
    from src.utils import menu
  File "menu.py", line 677, in <module>
    banner()
  File "menu.py", line 33, in banner
    print("""                                      __
  File "pydevd_io.py", line 33, in write
    with self._lock:
  File "pydevd_io.py", line 56, in __getattr__
    for r in self._redirect_to:
  File "pydevd_io.py", line 56, in __getattr__
    for r in self._redirect_to:
  File "pydevd_io.py", line 56, in __getattr__
    for r in self._redirect_to:
  [Previous line repeated 962 more times]
  File "pydevd_io.py", line 55, in __getattr__
    def __getattr__(self, name):
  File "pydevd_trace_dispatch_regular.py", line 469, in __call__
    return None if event == 'call' else NO_FTRACE
RecursionError: maximum recursion depth exceeded in comparison
```

**Comment by stasinopoulos** [comment]
Seems that something is wrong with Python environment.
