### ISSUE TITLE
Bug Report: Unhandled exception "AttributeError: module 'random' has no attribute 'choices'" (#979880ce)

### ISSUE THREAD

**Issue by commixreporter** [commixproject/commix#928]
```
Commix version: 4.0-dev#64
Python version: 3.5.2+
Operating system: posix
Command line: commix.py -r ************ 
```
```
Traceback (most recent call last):
  File "commix.py", line 36, in <module>
    main()
  File "commix.py", line 31, in main
    import src.core.main
  File \"main.py", line 891, in <module>
    response, url = url_response(url, http_request_method)
  File \"main.py", line 247, in url_response
    waf_request, waf_url = checks.check_waf(url, http_request_method)
  File \"checks.py", line 76, in check_waf
    payload = "".join(random.choices(string.ascii_uppercase, k=4)) + "=" + payload
AttributeError: module 'random' has no attribute 'choices'
```

**Comment by stasinopoulos** [comment]
The issue with ```
random.choices()
``` occurs only in python 3.5.
