### ISSUE TITLE
Bug Report: Unhandled exception "AttributeError: module 'sgmllib' has no attribute 'SGMLParser'" (#3bd47aee)

### ISSUE THREAD

**Issue by commixreporter** [commixproject/commix#962]
```
Commix version: 3.9-stable
Python version: 3.11.9
Operating system: posix
Command line: commix.py --wizard

```
```
Traceback (most recent call last):
  File "commix.py", line 35, in <module>
    main()
  File "commix.py", line 30, in main
    import src.core.main
  File "main.py", line 28, in <module>
    from src.utils import logs
  File "logs.py", line 25, in <module>
    from src.core.injections.controller import checks
  File "checks.py", line 39, in <module>
    from src.core.requests import requests
  File "requests.py", line 29, in <module>
    from src.utils import crawler
  File "crawler.py", line 31, in <module>
    from src.thirdparty.beautifulsoup.beautifulsoup import BeautifulSoup
  File "beautifulsoup.py", line 1056, in <module>
    class BeautifulStoneSoup(Tag, sgmllib.SGMLParser):
                                  ^^^^^^^^^^^^^^^^^^
AttributeError: module 'sgmllib' has no attribute 'SGMLParser'
```

**Comment by stasinopoulos** [comment]
Update to latest dev version and try again.
