### ISSUE TITLE
Error while ctrl+c pressed 

### ISSUE THREAD

**Issue by ArcherTannic** [commixproject/commix#986]
OS Windows 10
Commix(latest)
C:\Users\Archer\commix>python commix.py --url https://example.com --random-agent --drop-set-cookie --all --os=unix python commix.py --tamper=backslashes,backticks,base64encode,caret,dollaratsigns,doublequotes,hexencode,multiplespaces,nested,printf2echo,rev,singlequotes,slash2env,sleep2timeout,sleep2usleep,space2htab,space2ifs,space2plus,space2vtab,uninitializedvariable,xforwardedfor
Traceback (most recent call last):
  File "C:\Users\Archer\commix\commix.py", line 20, in <module>
    __import__("src.utils.version")
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Archer\commix\src\utils\version.py", line 17, in <module>
    from src.utils import settings
  File "C:\Users\Archer\commix\src\utils\settings.py", line 50, in <module>
    from src.thirdparty.colorama import Fore, Back, Style, init
  File "C:\Users\Archer\commix\src\thirdparty\colorama\__init__.py", line 2, in <module>
    from .initialise import init, deinit, reinit, colorama_text
  File "C:\Users\Archer\commix\src\thirdparty\colorama\initialise.py", line 6, in <module>
    from .ansitowin32 import AnsiToWin32
  File "C:\Users\Archer\commix\src\thirdparty\colorama\ansitowin32.py", line 6, in <module>
    from .ansi import AnsiFore, AnsiBack, AnsiStyle, Style
  File "C:\Users\Archer\commix\src\thirdparty\colorama\ansi.py", line 7, in <module>
    from src.utils import colors
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1018, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1114, in get_code
  File "<frozen importlib._bootstrap_external>", line 1213, in get_data
KeyboardInterrupt
^C

**Comment by stasinopoulos** [comment]
Hello @ArcherTannic 

Kindly provide as much detail as possible and use the following format:

```
## What's the problem (or question)?
<!--- If describing a bug, tell us what happens instead of the expected behavior -->
<!--- If suggesting a change/improvement, explain the difference from current behavior -->

## Do you have an idea for a solution?
<!--- Not obligatory, but suggest a fix/reason for the bug, -->
<!--- or ideas how to implement the addition or change -->

## How can we reproduce the issue?
<!--- Provide unambiguous set of steps to reproduce this bug. Include command to reproduce, if relevant (you can mask the sensitive data) -->
1.
2.
3.
4.

## What are the running context details?
<!--- Include as many relevant details about the running context you experienced the bug/problem in -->
* Installation method (e.g. `apt-get`, `git clone` or `zip`/`tar.gz`):
* Client OS (e.g. `Linux (Ubuntu)`)
* Program version (`python commix.py --version` or `commix --version` depending on installation): 
* Target OS (e.g. `Linux (Debian)`): 
* Command injection techniques found by commix (e.g. `classic (results-based)` and `time-based (blind)`):
* Results of manual target assessment (e.g. found that the payload `;echo \`id\`||echo $(whoami)` works):
* Relevant console output (if any):
* Exception traceback (if any):

```
